---
site_name: "LTRENT-2008 Beyond Basics: Practical SD-WAN Strategies for Route Leaking and Service Insertion"
site_description: "LTRENT-2008 Beyond Basics: Practical SD-WAN Strategies for Route Leaking and Service Insertion"
site_author: Waqas Ahmad Daar, Utsav Dutt
copyright: Copyright &copy; 2025 Cisco
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.instant
    - navigation.top
    - navigation.footer
    - search.suggest
    - content.code.copy
    - toc.integrate
  custom_dir: docs/overrides
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  logo: template_assets/cisco_logo.png
  favicon: template_assets/cisco_logo.png
extra:
  generator: false
extra_css:
  - stylesheets/extra.css
plugins:
  - search
  - with-pdf:
      cover_title: LTRENT-2008
      cover_subtitle: "Beyond Basics: Practical SD-WAN Strategies for Route Leaking and Service Insertion"
      cover_logo: template_assets/Cisco-Live-White-Blue-APJC.svg
  - glightbox:
      touchNavigation: true
      loop: false
      effect: fade
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: false
      skip_classes:
      - custom-skip-class-name
      auto_caption: true
      caption_position: top
markdown_extensions:
  - md_in_html
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - tables
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
nav:
  - Home: index.md
  - Lab:
      - Overview: overview.md
      - Getting Started: getting_started.md
      - Lab 1 - Route traffic from Stockholm to Sydney via local firewall in Stockholm: lab1_getting_started.md
      - Lab 2 - Route traffic from Stockholm to Sydney via London firewall in Same VRF: lab2_getting_started.md
      - Using Control Policy:
        - Lab 2 - Route traffic from Stockholm to Sydney via London firewall in Same VRF: lab2a_getting_started.md
      - Lab 3 - Getting Started: lab3_getting_started.md
      - Lab 4 - Getting Started: lab4_getting_started.md
      - Lab 5 - Getting Started: lab5_getting_started.md
      - Lab 6 - Getting Started: lab6_getting_started.md
      - Conclusion: conclusion.md
  - Topology: topologies.md
